plugins {
    id 'spring-boot-common-conventions'
}

dependencies {

    implementation 'kh.edu.istad:customer-domain-core'
    implementation 'kh.edu.istad:customer-application-service'
    implementation 'kh.edu.istad:customer-service-message'
    implementation 'kh.edu.istad:customer-service-persistence'
    implementation 'kh.edu.istad:customer-service-restapi'

    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
//    runtimeOnly 'com.h2database:h2'
    runtimeOnly 'org.postgresql:postgresql'
}