plugins {
    id 'spring-boot-common-conventions'
}

dependencies {
    // Core dependency for building web applications (includes Tomcat and Spring MVC)
    implementation 'org.springframework.boot:spring-boot-starter-web'

    // Recommended: Production-ready features like health checks and monitoring
    implementation 'org.springframework.boot:spring-boot-starter-actuator'

    // Testing framework (Includes JUnit, Mockito, and Spring Test utilities)
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
