pluginManagement {
    includeBuild('../build-logic')

    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}
dependencyResolutionManagement {
    repositories {
        mavenCentral()
    }
}
rootProject.name = 'istad-common'
include 'istad-common-domain'
include 'istad-common-restapi'
